### ISSUE TITLE
How to convert the below curl to postman or jquery request

### ISSUE THREAD

**Issue by 7seven7lst** [talakoski/rails-devise-jwt#1]
Hi. 
I followed the readme and 
curl -i --header "Content-Type: application/json" -X POST -d '{"email":"admin@example.com","password":"12345678"}' http://localhost:3000/api/v1/authentication_tokens/create
does not return any token  in the response.

**Comment by talakoski** [comment]
Hi,

Maybe you didn't create the admin user? In can eg. use Rails console to create the user:
```
User.create!(email: "admin@example.com", password: "12345678")
```

And to answer you original question about Postman: add the `Authorication` to the Headers section in the Postman request :)
